module.exports = {
    env: {
        es6: true,
        node: true,
        browser: true,
        jest: true,
    },

    plugins: [],

    parserOptions: {
        ecmaVersion: 6,
        sourceType: "module",
        ecmaFeatures: {
            modules: true,
        },
    },

    rules: {
        "array-callback-return": ["error"],
        "constructor-super": ["error"],
        "for-direction": ["error"],
        "getter-return": ["error"],
        "no-async-promise-executor": ["error"],
        "no-await-in-loop": ["warn"],
        "no-class-assign": ["error"],
        "no-compare-neg-zero": ["error"],
        "no-cond-assign": ["error"],
        "no-const-assign": ["error"],
        "no-constant-binary-expression": ["error"],
        "no-constant-condition": ["error"],
        "no-constructor-return": ["error"],
        "no-control-regex": ["error"],
        "no-debugger": ["warn"],
        "no-dupe-args": ["error"],
        "no-dupe-class-members": ["error"],
        "no-dupe-else-if": ["error"],
        "no-dupe-keys": ["error"],
        "no-duplicate-case": ["error"],
        "no-duplicate-imports": ["error"],
        "no-empty-character-class": ["error"],
        "no-empty-pattern": ["error"],
        "no-ex-assign": ["error"],
        "no-fallthrough": ["error"],
        "no-func-assign": ["error"],
        "no-import-assign": ["error"],
        "no-inner-declarations": ["error"],
        "no-invalid-regexp": ["error"],
        "no-irregular-whitespace": ["error"],
        "no-loss-of-precision": ["error"],
        "no-misleading-character-class": ["error"],
        "no-new-symbol": ["error"],
        "no-obj-calls": ["error"],
        "no-promise-executor-return": ["error"],
        "no-prototype-builtins": ["error"],
        "no-self-assign": ["error"],
        "no-self-compare": ["error"],
        "no-setter-return": ["error"],
        "no-sparse-arrays": ["error"],
        "no-template-curly-in-string": ["error"],
        "no-this-before-super": ["error"],
        "no-undef": ["error"],
        "no-unexpected-multiline": ["error"],
        "no-unreachable": ["error"],
        "no-unsafe-finally": ["error"],
        "no-unsafe-optional-chaining": ["error"],
        "no-use-before-define": ["error"],
        "no-useless-backreference": ["error"],
        "use-isnan": ["error"],

        // Suggestions
        "accessor-pairs": ["error"],
        "arrow-body-style": ["error", "as-needed"],
        camelcase: ["error"],
        "class-methods-use-this": ["error"],
        curly: ["error", "multi-line"],
        "default-case": ["error"],
        "default-case-last": ["error"],
        "default-param-last": ["error"],
        "dot-notation": ["error"],
        eqeqeq: ["error", "always"],
        "grouped-accessor-pairs": ["error"],
        "id-length": ["error", { min: 2, max: 50 }],
        "init-declarations": ["error", "always"],
        "max-classes-per-file": ["error", 1],
        "max-depth": ["error", 5],
        "max-lines": ["error", 800],
        "max-nested-callbacks": ["error", 3],
        "max-params": ["error", 2],
        "new-cap": ["error", { newIsCap: true }],
        "no-alert": ["error"],
        "no-bitwise": ["error"],
        "no-caller": ["error"],
        "no-case-declarations": ["error"],
        "no-delete-var": ["error"],
        "no-else-return": ["error"],
        "no-empty": ["error", { allowEmptyCatch: true }],
        "no-eq-null": ["error"],
        "no-eval": ["error"],
        "no-extend-native": ["error"],
        "no-floating-decimal": ["error"],
        "no-extra-semi": ["error"],
        "no-global-assign": ["error"],
        "no-implicit-coercion": ["error", { allow: ["!!"] }],
        "no-inline-comments": ["error"],
        "no-invalid-this": ["error"],
        "no-lone-blocks": ["error"],
        "no-mixed-operators": ["error"],
        "no-multi-assign": ["error"],
        "no-new": ["error"],
        "no-new-wrappers": ["error"],
        "no-octal-escape": ["error"],
        "no-param-reassign": ["error"],
        "no-redeclare": ["error"],
        "no-regex-spaces": ["error"],
        "no-return-assign": ["error"],
        "no-return-await": ["error"],
        "no-shadow-restricted-names": ["error"],
        "no-throw-literal": ["error"],
        "no-undef-init": ["error"],
        "no-useless-catch": ["error"],
        "no-useless-constructor": ["error"],
        "no-useless-escape": ["error"],
        "no-useless-rename": ["error"],
        "no-useless-return": ["error"],
        "no-var": ["error"],
        "no-with": ["error"],
        "object-shorthand": ["error", "always"],
        "one-var": ["error", "never"],
        "prefer-const": ["error"],
        "prefer-arrow-callback": ["error"],
        "prefer-object-spread": ["error"],
        "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
        "prefer-rest-params": ["error"],
        "prefer-spread": ["error"],
        "prefer-template": ["error"],
        "quote-props": ["error", "as-needed"],
        "require-await": ["error"],
        "require-yield": ["error"],
        "spaced-comment": ["error", "always"],
        "symbol-description": ["error"],
        "vars-on-top": ["error"],
        yoda: ["error"],

        // Layout & Formatting
        "array-bracket-newline": ["error", "consistent"],
        "array-bracket-spacing": ["error", "never"],
        "arrow-parens": ["error", "as-needed"],
        "arrow-spacing": ["error"],
        "block-spacing": ["error"],
        "brace-style": ["error"],
        "comma-dangle": ["error", "never"],
        "comma-spacing": ["error", { before: false, after: true }],
        "comma-style": ["error", "last"],
        "computed-property-spacing": ["error", "never"],
        "dot-location": ["error", "property"],
        "eol-last": ["error", "always"],
        "func-call-spacing": ["error", "never"],
        "function-call-argument-newline": ["error", "consistent"],
        "function-paren-newline": ["error", "consistent"],
        "generator-star-spacing": ["error", { before: false, after: true }],
        "implicit-arrow-linebreak": ["error", "beside"],
        indent: ["error", 4],
        "jsx-quotes": ["error", "prefer-double"],
        "key-spacing": ["error", { beforeColon: false, afterColon: true }],
        "line-comment-position": ["error", { position: "above" }],
        "linebreak-style": ["error", "unix"],
        "lines-around-comment": [
            "error",
            { beforeBlockComment: true, beforeLineComment: true },
        ],
        "lines-between-class-members": ["error", "always"],
        "max-len": ["error", { code: 200, comments: 80 }],
        "multiline-ternary": ["error"],
        "newline-per-chained-call": ["error", { ignoreChainWithDepth: 2 }],
        "no-mixed-spaces-and-tabs": ["error"],
        "no-multi-spaces": ["error"],
        "no-multiple-empty-lines": ["error", { max: 1 }],
        "no-tabs": ["error"],
        "no-trailing-spaces": ["error"],
        "no-whitespace-before-property": ["error"],
        "object-curly-spacing": ["error", "always"],
        "object-property-newline": [
            "error",
            { allowAllPropertiesOnSameLine: true },
        ],
        "operator-linebreak": ["error", "before"],
        quotes: ["error", "single", { allowTemplateLiterals: true }],
        "rest-spread-spacing": ["error", "never"],
        semi: ["error", "always"],
        "semi-spacing": ["error"],
        "semi-style": ["error", "last"],
        "space-before-blocks": ["error"],
        "space-before-function-paren": ["error", "never"],
        "space-in-parens": ["error", "never"],
        "space-infix-ops": ["error"],
        "space-unary-ops": ["error"],
        "switch-colon-spacing": ["error"],
        "template-curly-spacing": ["error"],
        "template-tag-spacing": ["error"],
        "yield-star-spacing": ["error", "after"],
    },
};
